/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-09 03:58:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   // 세션 방식
   String id = (String)session.getAttribute("id");
   session.setMaxInactiveInterval(30*60); // 30분 (30*60초)  

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Jekyll v4.0.1\">\r\n");
      out.write("    <title>Board Page</title>\r\n");
      out.write("    \r\n");
      out.write("   \t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" >\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/board.css\">\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write(" \t<!-- 헤더 임포트 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t    <nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse\">\r\n");
      out.write("\t      <div class=\"sidebar-sticky pt-3\">\r\n");
      out.write("\t        <ul class=\"nav flex-column\">\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"home\"></span>\r\n");
      out.write("\t              Dashboard <span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"file\"></span>\r\n");
      out.write("\t              Inbox\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"users\"></span>\r\n");
      out.write("\t              Subscription\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"bar-chart-2\"></span>\r\n");
      out.write("\t              Reports\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"layers\"></span>\r\n");
      out.write("\t              Profits\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t\r\n");
      out.write("\t        <h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t          <span>Saved reports</span>\r\n");
      out.write("\t          <a class=\"d-flex align-items-center text-muted\" href=\"#\" aria-label=\"Add a new report\">\r\n");
      out.write("\t            <span data-feather=\"plus-circle\"></span>\r\n");
      out.write("\t          </a>\r\n");
      out.write("\t        </h6>\r\n");
      out.write("\t        <ul class=\"nav flex-column mb-2\">\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"file-text\"></span>\r\n");
      out.write("\t              Current month\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"file-text\"></span>\r\n");
      out.write("\t              Last quarter\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"file-text\"></span>\r\n");
      out.write("\t              Social engagement\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\t              <span data-feather=\"file-text\"></span>\r\n");
      out.write("\t              Year-end\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </nav>\r\n");
      out.write("\t\r\n");
      out.write("\t    <main role=\"main\" class=\"col-md-9 ml-sm-auto col-lg-10 px-md-4\">\r\n");
      out.write("\t      <div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom\">\r\n");
      out.write("\t        <h1 class=\"h2\">조회수</h1>\r\n");
      out.write("\t        <div class=\"btn-toolbar mb-2 mb-md-0\">\r\n");
      out.write("\t          <div class=\"btn-group mr-2\">\r\n");
      out.write("\t            <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t            <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Export</button>\r\n");
      out.write("\t          </div>\r\n");
      out.write(" \t          <button type=\"button\" class=\"btn btn-sm btn-outline-secondary dropdown-toggle\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t            <span data-feather=\"calendar\"></span>\r\n");
      out.write("\t            This week\r\n");
      out.write("\t          </button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t      <canvas class=\"my-4 w-100\" id=\"myChart\" width=\"900\" height=\"380\"></canvas>\r\n");
      out.write("\t\r\n");
      out.write("\t    </main>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/board.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
