/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-09 03:58:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lecture_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

   // 세션 방식
   String id = (String)session.getAttribute("id");
   session.setMaxInactiveInterval(30*60); // 30분(30*60초)

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Jekyll v4.0.1\">\r\n");
      out.write("    <title>Lecture Page</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap and CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/lecture.css\" >\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- 헤더 임포트 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<main role=\"main\">\r\n");
      out.write("\t  <section class=\"jumbotron text-center\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t      <h1>Online Lecture Services</h1>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <p class=\"lead text-muted\">취향저격 강의 서비스 - 보다 나은 가치추구를 위한 무한 노력! <br>창의교육! 미래방송! 이제는 교육도 골라듣자! <br>대한민국 1등 온라인 강의 플랫폼</p>\r\n");
      out.write("\t      <p>\r\n");
      out.write("\t        <a href=\"#\" class=\"btn btn-primary my-2\">강의 등록 문의</a>\r\n");
      out.write("\t        <a href=\"#\" class=\"btn btn-secondary my-2\">광고 등록 문의</a>\r\n");
      out.write("\t      </p>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </section>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 썸네일 시작 -->\r\n");
      out.write("\t  <div class=\"album py-5 bg-light\">\r\n");
      out.write("\t    <div class=\"container\">\r\n");
      out.write("\t      <div class=\"row\">\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t          \t<img alt=\"\" src=\"img/ch6_1.PNG\" class=\"youtube_img\" >\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">ch6-1 객체지향 언어에 대한 강의입니다. 객체지향 언어와 공부방법에 대한 강의입니다.</p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=CXuA31XcBZ0'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">21 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t          <img alt=\"\" src=\"img/ch6_2.PNG\" class=\"youtube_img\" >\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">ch6-2~4 클래스와객체에 대한 강의입니다.<br><br><br></p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=jnhvQr1iDRE'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">14 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t            <img alt=\"\" src=\"img/ch6_3.PNG\" class=\"youtube_img\" >\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">ch6-6, 7 객체의 생성과 사용 방법에 대한 강의입니다.<br><br></p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=p1ZZnM715ao'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">27 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t            <img alt=\"\" src=\"img/dog1.PNG\" class=\"youtube_img\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">유기견을 임시 보호 하다가 입양 보내면 다시 버려진다고 생각하나요?｜강형욱의 소소한 Q&A</p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=YdiiFX1T8ZY'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">2 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t            <img alt=\"\" src=\"img/dog2.PNG\" class=\"youtube_img\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">강아지들이 노즈워크를 계속하면 질리나요?｜강형욱의 소소한 Q&A<br><br></p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=VYOXggvZSHI'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">3 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t          \t<img alt=\"\" src=\"img/dog3.PNG\" class=\"youtube_img\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">강아지가 헥헥댈 때 웃는 건지 긴장한 건지 구분할 수 있나요? ｜강형욱의 소소한 Q&A<br><br></p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=kYUGSfyo2mI'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">2 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t            <img alt=\"\" src=\"img/cook1.png\" class=\"youtube_img\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">오늘은 집에서 간단하게 해드실 수 있는 집밥 레시피를 알려드릴게요. 달걀이 소스랑 만나서 아~주 부드럽습니다!</p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=AlK2Gl6kHZI'\"class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">17 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t            <img alt=\"\" src=\"img/cook2.png\" class=\"youtube_img\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">짜장 덮밥에 달걀 후라이 하나 올리면 끝! 이거 완전 밥도둑입니다! 만들어 놓은 짜장소스로 덮밥 만들어 보세요~</p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=_O4tvQtZDiU'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">6 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"col-md-4\">\r\n");
      out.write("\t          <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t            <img alt=\"\" src=\"img/cook3.png\" class=\"youtube_img\">\r\n");
      out.write("\t            <div class=\"card-body\">\r\n");
      out.write("\t              <p class=\"card-text\">쉽게 구할 수 있는 재료로 만든 김치볶음밥의 업그레이드 버전, 김치밥! 강식당2 속 그 메뉴, 직접 만들어보는 건 어떨까요?</p>\r\n");
      out.write("\t              <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" onclick=\"location.href='https://www.youtube.com/watch?v=R6IT_f0XPT8'\" class=\"btn btn-sm btn-outline-secondary\">View</button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-sm btn-outline-secondary\">Share</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <small class=\"text-muted\">9 mins</small>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
