/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-04 02:03:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	//쿠키 가져오기
	Cookie[] cookies = request.getCookies(); // cookies가 null 수 있음에 주의
	String id = "";
	String remember = "";
	
	if(cookies != null) {
		for(int i=0;i<cookies.length;i++) {
	        if(cookies[i].getName().equals("id")) {
	        	id = cookies[i].getValue();	// 아이디 쿠키값 저장
	         	remember = "checked";		// 체크 박스 체크할 부분
	        }
  		}
	}
	
	// 권한 메세지 가져와 뿌리기
	String errMsg = request.getParameter("errMsg");
	if(errMsg !=null) {
    	out.println(
    		"<script> alert('"+ errMsg +"'); </script>"
    	);
    }
	
	// 메세지 가져와 뿌리기(아이디 비밀번호 틀렸을 때) 
   	String msg = request.getParameter("msg");
	msg = msg!=null? msg : "";
   
   String url = request.getParameter("url");


      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("   <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("   \r\n");
      out.write("   <link href=\"https://fonts.googleapis.com/css?family=Kaushan+Script\" rel=\"stylesheet\">\r\n");
      out.write("   <link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/loginForm.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("         <div class=\"col-md-5 mx-auto\">\r\n");
      out.write("         <div id=\"first\">\r\n");
      out.write("            <div class=\"myform form \">\r\n");
      out.write("                <div class=\"logo mb-3\">\r\n");
      out.write("                   <div class=\"col-md-12 text-center\">\r\n");
      out.write("                     <h1>Login</h1>\r\n");
      out.write("                   </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                <form action=\"/Session/LoginAction\" method=\"post\" name=\"login\">\r\n");
      out.write("                \t<div class=\"form-group\">\r\n");
      out.write("                \t\t<!-- 히든으로 board의 값(어느 게시판인지) 보내기 -->\r\n");
      out.write("                \t\t<input type=\"hidden\" name=\"url\" value=\"");
      out.print(url);
      out.write("\">\r\n");
      out.write("                       \t<label for=\"exampleInputEmail1\">Id</label>\r\n");
      out.write("                        <input type=\"text\" name=\"id\" value=\"");
      out.print(id );
      out.write("\" class=\"form-control\" id=\"id\" placeholder=\"Enter id\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    \t<label for=\"exampleInputEmail1\">Password</label>\r\n");
      out.write("                        <input type=\"password\" name=\"pwd\" id=\"pwd\"  class=\"form-control\" placeholder=\"Enter Password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("\t\t\t        \t<input type=\"checkbox\" class=\"custom-control-input\" id=\"save-info\" ");
      out.print(remember );
      out.write(" name=\"remember\" value=\"remember\">\r\n");
      out.write("\t\t\t        \t<label class=\"custom-control-label\" for=\"save-info\">Remember ID</label>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                       <label id=\"msg\">");
      out.print(msg );
      out.write("</label>\r\n");
      out.write("                       <p class=\"text-center\">By signing up you accept our <a href=\"#\">Terms Of Use</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12 text-center \">\r\n");
      out.write("                       <button type=\"submit\" class=\" btn btn-block mybtn btn-primary tx-tfm\">Login</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12 \">\r\n");
      out.write("                       <div class=\"login-or\">\r\n");
      out.write("                          <hr class=\"hr-or\">\r\n");
      out.write("                          <span class=\"span-or\">or</span>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12 mb-3\">\r\n");
      out.write("                       <p class=\"text-center\">\r\n");
      out.write("                          <a href=\"javascript:void();\" class=\"google btn mybtn\"><i class=\"fa fa-google-plus\">\r\n");
      out.write("                          </i> Signup using Google\r\n");
      out.write("                          </a>\r\n");
      out.write("                       </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                       <p class=\"text-center\">Don't have account? <a href=\"/Session/registerForm.jsp\" id=\"signup\">Sign up here</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
