/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-01 03:15:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Jekyll v4.0.1\">\r\n");
      out.write("    <title>Checkout example · Bootstrap</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/4.5/examples/checkout/\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"/docs/4.5/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    .container {\r\n");
      out.write("\t  max-width: 960px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.lh-condensed { line-height: 1.25; }\r\n");
      out.write("\t    \r\n");
      out.write("     .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"bg-light\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("  <div class=\"py-5 text-center\">\r\n");
      out.write("    <img class=\"d-block mx-auto mb-4\" src=\"/docs/4.5/assets/brand/bootstrap-solid.svg\" alt=\"\" width=\"72\" height=\"72\">\r\n");
      out.write("    <h2>Checkout form</h2>\r\n");
      out.write("    <p class=\"lead\">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-4 order-md-2 mb-4\">\r\n");
      out.write("      <h4 class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("        <span class=\"text-muted\">Your cart</span>\r\n");
      out.write("        <span class=\"badge badge-secondary badge-pill\">3</span>\r\n");
      out.write("      </h4>\r\n");
      out.write("      <ul class=\"list-group mb-3\">\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-condensed\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\">Product name</h6>\r\n");
      out.write("            <small class=\"text-muted\">Brief description</small>\r\n");
      out.write("          </div>\r\n");
      out.write("          <span class=\"text-muted\">$12</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-condensed\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\">Second product</h6>\r\n");
      out.write("            <small class=\"text-muted\">Brief description</small>\r\n");
      out.write("          </div>\r\n");
      out.write("          <span class=\"text-muted\">$8</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-condensed\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\">Third item</h6>\r\n");
      out.write("            <small class=\"text-muted\">Brief description</small>\r\n");
      out.write("          </div>\r\n");
      out.write("          <span class=\"text-muted\">$5</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between bg-light\">\r\n");
      out.write("          <div class=\"text-success\">\r\n");
      out.write("            <h6 class=\"my-0\">Promo code</h6>\r\n");
      out.write("            <small>EXAMPLECODE</small>\r\n");
      out.write("          </div>\r\n");
      out.write("          <span class=\"text-success\">-$5</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between\">\r\n");
      out.write("          <span>Total (USD)</span>\r\n");
      out.write("          <strong>$20</strong>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <form class=\"card p-2\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" placeholder=\"Promo code\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-secondary\">Redeem</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-8 order-md-1\">\r\n");
      out.write("      <h4 class=\"mb-3\">Billing address</h4>\r\n");
      out.write("      <form class=\"needs-validation\" novalidate>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 mb-3\">\r\n");
      out.write("            <label for=\"firstName\">First name</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"firstName\" placeholder=\"\" value=\"\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Valid first name is required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 mb-3\">\r\n");
      out.write("            <label for=\"lastName\">Last name</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"lastName\" placeholder=\"\" value=\"\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Valid last name is required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label for=\"username\">Username</label>\r\n");
      out.write("          <div class=\"input-group\">\r\n");
      out.write("            <div class=\"input-group-prepend\">\r\n");
      out.write("              <span class=\"input-group-text\">@</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"username\" placeholder=\"Username\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\" style=\"width: 100%;\">\r\n");
      out.write("              Your username is required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label for=\"email\">Email <span class=\"text-muted\">(Optional)</span></label>\r\n");
      out.write("          <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"you@example.com\">\r\n");
      out.write("          <div class=\"invalid-feedback\">\r\n");
      out.write("            Please enter a valid email address for shipping updates.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label for=\"address\">Address</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"address\" placeholder=\"1234 Main St\" required>\r\n");
      out.write("          <div class=\"invalid-feedback\">\r\n");
      out.write("            Please enter your shipping address.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label for=\"address2\">Address 2 <span class=\"text-muted\">(Optional)</span></label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"address2\" placeholder=\"Apartment or suite\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-5 mb-3\">\r\n");
      out.write("            <label for=\"country\">Country</label>\r\n");
      out.write("            <select class=\"custom-select d-block w-100\" id=\"country\" required>\r\n");
      out.write("              <option value=\"\">Choose...</option>\r\n");
      out.write("              <option>United States</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Please select a valid country.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 mb-3\">\r\n");
      out.write("            <label for=\"state\">State</label>\r\n");
      out.write("            <select class=\"custom-select d-block w-100\" id=\"state\" required>\r\n");
      out.write("              <option value=\"\">Choose...</option>\r\n");
      out.write("              <option>California</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Please provide a valid state.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-3\">\r\n");
      out.write("            <label for=\"zip\">Zip</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"zip\" placeholder=\"\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Zip code required.\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mb-4\">\r\n");
      out.write("        <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("          <input type=\"checkbox\" class=\"custom-control-input\" id=\"same-address\">\r\n");
      out.write("          <label class=\"custom-control-label\" for=\"same-address\">Shipping address is the same as my billing address</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("          <input type=\"checkbox\" class=\"custom-control-input\" id=\"save-info\">\r\n");
      out.write("          <label class=\"custom-control-label\" for=\"save-info\">Save this information for next time</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <h4 class=\"mb-3\">Payment</h4>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-block my-3\">\r\n");
      out.write("          <div class=\"custom-control custom-radio\">\r\n");
      out.write("            <input id=\"credit\" name=\"paymentMethod\" type=\"radio\" class=\"custom-control-input\" checked required>\r\n");
      out.write("            <label class=\"custom-control-label\" for=\"credit\">Credit card</label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"custom-control custom-radio\">\r\n");
      out.write("            <input id=\"debit\" name=\"paymentMethod\" type=\"radio\" class=\"custom-control-input\" required>\r\n");
      out.write("            <label class=\"custom-control-label\" for=\"debit\">Debit card</label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"custom-control custom-radio\">\r\n");
      out.write("            <input id=\"paypal\" name=\"paymentMethod\" type=\"radio\" class=\"custom-control-input\" required>\r\n");
      out.write("            <label class=\"custom-control-label\" for=\"paypal\">PayPal</label>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 mb-3\">\r\n");
      out.write("            <label for=\"cc-name\">Name on card</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"cc-name\" placeholder=\"\" required>\r\n");
      out.write("            <small class=\"text-muted\">Full name as displayed on card</small>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Name on card is required\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 mb-3\">\r\n");
      out.write("            <label for=\"cc-number\">Credit card number</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"cc-number\" placeholder=\"\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Credit card number is required\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-3 mb-3\">\r\n");
      out.write("            <label for=\"cc-expiration\">Expiration</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"cc-expiration\" placeholder=\"\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Expiration date required\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-3\">\r\n");
      out.write("            <label for=\"cc-cvv\">CVV</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"cc-cvv\" placeholder=\"\" required>\r\n");
      out.write("            <div class=\"invalid-feedback\">\r\n");
      out.write("              Security code required\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"mb-4\">\r\n");
      out.write("        <button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\">Continue to checkout</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"my-5 pt-5 text-muted text-center text-small\">\r\n");
      out.write("    <p class=\"mb-1\">&copy; 2017-2020 Company Name</p>\r\n");
      out.write("    <ul class=\"list-inline\">\r\n");
      out.write("      <li class=\"list-inline-item\"><a href=\"#\">Privacy</a></li>\r\n");
      out.write("      <li class=\"list-inline-item\"><a href=\"#\">Terms</a></li>\r\n");
      out.write("      <li class=\"list-inline-item\"><a href=\"#\">Support</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("      <script>window.jQuery || document.write('<script src=\"/docs/4.5/assets/js/vendor/jquery.slim.min.js\"><\\/script>')</script><script src=\"/docs/4.5/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"form-validation.js\"></script></body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
